[package]
name = "calr"
version = "0.1.0"
authors = ["rsookram <rashadsookram@gmail.com>"]
edition = "2018"
description = "Command-line tool which displays a calendar"

[dependencies]
chrono = "0.4"
structopt = "0.3"

[profile.release]
lto = true
codegen-units = 1
