[package]
name = "calr"
version = "0.1.0"
authors = ["rsookran <rashadsookram@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
structopt = "0.2"

[profile.release]
lto = true
codegen-units = 1
